format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$kubernetes\
$helm\
$docker\
$gcloud\
$go\
$aws\
$cmd_duration $jobs $time\
$line_break\
$character"""

add_newline = true

#https://github.com/morhetz/gruvbox
palette = "gruvbox-dark"

[character]
format = "$symbol "
success_symbol = "[ î®‹](bold green) "
error_symbol = "[ î®‰](bold red) "

[palettes.gruvbox-dark]
red = "#CC241D"
green = "#98971A"
yellow = "#D79921"
blue = "#458588"
purple = "#B16286"
aqua = "#689D6A" #green
orange = "#D65D0E"
gray = "#A89984"
bg = "#282828"
bg0_h = "#1D2021"
bg1 = "#3C3836"
bg2 = "#504945"
bg3 = "#665C54"
bg4 = "#7C6F64"

[palettes.tokyo-night]
background = "#1a1b26"
foreground = "#a9b1d6"
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"
bright-black = "#444b6a"
bright-red = "#ff7a93"
bright-green = "#b9f27c"
bright-yellow = "#ff9e64"
bright-blue = "#7da6ff"
bright-magenta = "#bb9af7"
bright-cyan = "#0db9d7"
bright-white = "#acb0d0"

[git_status]
style = "aqua"

[kubernetes]
disabled = false
symbol = "ï´± "
format = '[$symbol$context( \($namespace\))]($style) '
style = "blue"

[kubernetes.context_aliases]
"core-stg.*" = "STG"
"core-prd.*" = "PRD"
"core-dev.*" = "DEV"

[helm]
disabled = false
symbol = "î«¦ "
format = "[$symbol($version )]($style)"

[time]
disabled = false
format = "[$time]($style)"
style = "gray"

[cmd_duration]

[aws]
disabled = false
symbol = "îŒ½  "

[buf]
disabled = true
symbol = "ï’ "

[conda]
disabled = true
symbol = "ï„Œ "

[directory]
truncation_length = 6
disabled = false
style = "#D79921"
read_only = " ï ½"
read_only_style = "#CC241D"

[docker_context]
symbol = "ïŒˆ "

[elixir]
disabled = true
symbol = "î‰µ "

[elm]
disabled = true
symbol = "î˜¬ "

[fill]
symbol = " "
style = "#282828"
[git_branch]
symbol = "ï˜ "
[gcloud]
disabled = true
[golang]
symbol = "î˜§ "

[haskell]
disabled = true
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
disabled = true
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ï¡š "

[meson]
symbol = "ï¨¶ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "
